spring.application.name=nexcare-backend


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nexcare_db
spring.datasource.username=postgres
spring.datasource.password=301970


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret = ThisIsSecretKeyForNexCareApplication01032002
jwt.expiration = 3600000

logging.level.org.springframework.security=DEBUG

#Cloudinary Configuration
cloudinary.cloud-name= g6n8rfen
cloudinary.api-key=318571851756151
cloudinary.api-secret=A8UvhLwGZX5TvH81at-A9aR7f0g

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB