spring.application.name=nexcare-backend


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nexcare_db
spring.datasource.username=postgres
spring.datasource.password=301970


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT Configuration
jwt.secret = ThisIsSecretKeyForNexCareApplication01032002
jwt.expiration = 3600000

logging.level.org.springframework.security=DEBUG